# syntax=docker/dockerfile:1.7

FROM node:22-alpine AS deps

WORKDIR /app

RUN apk add --no-cache yarn

ARG VITE_APP_NAME="ILMO."
ARG VITE_APP_PRIMARY_COLOR="#005FCC"
ARG VITE_APP_SECONDARY_COLOR="#1D1D1F"

ENV VITE_APP_NAME=$VITE_APP_NAME
ENV VITE_APP_PRIMARY_COLOR=$VITE_APP_PRIMARY_COLOR
ENV VITE_APP_SECONDARY_COLOR=$VITE_APP_SECONDARY_COLOR

COPY package.json yarn.lock ./

RUN --mount=type=cache,target=/usr/local/share/.cache/yarn,sharing=locked \
    yarn install --frozen-lockfile

FROM node:22-alpine AS build

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules

COPY . .

RUN yarn messages:compile \
 && yarn build:ssr:client \
 && yarn build:ssr:server

FROM node:22-alpine AS prod-deps

WORKDIR /app

COPY package.json yarn.lock ./

RUN --mount=type=cache,target=/usr/local/share/.cache/yarn,sharing=locked \
    yarn install --frozen-lockfile --production

FROM node:22-alpine AS runtime

ENV NODE_ENV=production

WORKDIR /app

COPY --from=prod-deps /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY package.json yarn.lock server.js ./
COPY src ./src
COPY public ./public

EXPOSE 5678

CMD ["yarn", "start"]
